### ISSUE TITLE
Adhoc Filters with CSVServer

### ISSUE THREAD

**Issue by nshree87** [michaeldmoore/CSVServer#12]
Hi,
 I am new to Grafana, i was trying with simpleJson datasource, found this , my question is do csvserver has "adhocFilter" feature, if so how should it be accessed?
Thanks,
Nagashree

**Comment by michaeldmoore** [comment]
No, but Under Grafana 7.x, the new Query transformation system will probably do what you want.  And that works for ALL datasources.
