### ISSUE TITLE
Unable to overwrite the host address

### ISSUE THREAD

**Issue by SankarMittapally** [michaeldmoore/CSVServer#15]
It would be great, if you provide me an option to overwrite the server address from 127.0.0.1 to real ip. I am planning to use it for docker containers for testing.

**Comment by michaeldmoore** [comment]
After some quick research (I'm no expert in this area), I think the fix you
need is to change line 72 in CSVServer.js

from
   app.listen(port, err => {

to
   app.listen(port, '0.0.0.0', err => {

Let me know if this works, and I'll add it to the next release.


(This comes from
https://stackoverflow.com/questions/61822353/fastify-not-working-on-docker-kubernetes
)

Cheers
Michael Moore

**Comment by SankarMittapally** [comment]
it worked, thanks for quick reply.
