### ISSUE TITLE
Unable to read the files from directory

### ISSUE THREAD

**Issue by SankarMittapally** [michaeldmoore/CSVServer#16]
1601457925699] INFO  (16358 on ): incoming request
    reqId: 3
    req: {
      "method": "POST",
      "url": "/search",
      "hostname": "10.24.14.0:4000",
      "remoteAddress": "172.17.0.4",
      "remotePort": 53714
    }
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:191:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

**Comment by michaeldmoore** [comment]
I agree, this should be handled better, but the error message 'EISDIR' is
simple enough - the directory you are specifying, wherever that is, is NOT
a directory.

My first google search on EISDIR returns this:

https://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read


Hope this helps - if not, give me some real details to work on, such as you
environment, the text printed to the console, your configuration file
contents etc.
